# This file is heavily inspired by these pages:
# - https://circleci.com/docs/2.0/language-haskell/
# - https://circleci.com/blog/publishing-to-github-releases-via-circleci/
#
version: 2
jobs:
  publish:
    docker:
      - image: fpco/stack-build-small:lts-14
    steps:
      - attach_workspace:
          at: ws
      - run:
          name: Install curl
          command: apt-get update && apt-get -qq -y install curl libpq-dev
      - run:
          name: Download ghr
          command: |
            curl -sSLO https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_386.tar.gz
            curl -sSLO https://github.com/tcnksm/ghr/releases/download/v0.12.0/v0.12.0_SHASUMS
            sha256sum --check --ignore-missing v0.12.0_SHASUMS
            tar --strip-components=1 -zxvf ghr_v0.12.0_linux_386.tar.gz ghr_v0.12.0_linux_386/ghr
      - run:
          name: Publish Release on GitHub
          command: |
            mkdir result
            cp ws/postgres-websockets.sha256 ws/postgres-websockets ./result/
            VERSION=$(awk '/^version: / { print $2 };' < ws/postgres-websockets.cabal)
            ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./result/

  build-test:
    docker:
      - image: fpco/stack-build:lts-14.27
      - image: postgres:11-alpine
        environment:
          POSTGRES_DB: postgres_ws_test
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - postgres-websockets-v2-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve and update dependencies
          command: stack setup
      - run:
          name: Install Cabal and hlint
          command: stack install --system-ghc --resolver=lts-14.27 Cabal hlint
      - save_cache:
          name: Cache Dependencies
          key: postgres-websockets-v2-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
      - run:
          name: Build the dependencies and the library
          command: stack --silent build
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack --silent install
      - run:
          name: Calculate and save checksum
          command: sha256sum ~/.local/bin/postgres-websockets > ~/.local/bin/postgres-websockets.sha256
      - run:
          name: Save cabal file to preserve version
          command: cp postgres-websockets.cabal ~/.local/bin/
      - save_cache:
          name: Cache Dependencies
          key: postgres-websockets-v2-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
      - persist_to_workspace:
          root: ~/.local/bin/
          paths: 
            - "postgres-websockets"
            - "postgres-websockets.sha256"
            - "postgres-websockets.cabal"

workflows:
  version: 2
  main:
    jobs:
      - build-test
      - publish:
          requires:
            - build-test
          filters:
            branches:
              only: master
