name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  stack:
    name: stack / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.5.1"]
        ghc: ["9.0.2"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: roottoor
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres_ws_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.ghc }}-stack-v3

    - name: Build Dependencies
      run: |
        stack build --system-ghc --test --no-run-tests --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --no-run-tests

    - name: Test
      run: |
        stack test --system-ghc

    - name: ${{ matrix.os }} binaries
      uses: actions/upload-artifact@v2
      with:
        name: Store binaries
        path: |
          .stack-work/dist/**/postgres-websockets